#ifndef _EDIT_H_
#define _EDIT_H_


int draw_edit01(struct Parameter *abc);//The first in edit:choose area
int draw_edit02(struct Parameter *abc);//The Second in edit:define size and shape of the field
int draw_edit03(struct Parameter *abc);//Choose the type of tractors and cotton
//void press_edit();//add the press moudule

void edit();

// typedef struct
// {
//     char name[10];//名字
//     int place;//产区
// 	char shape;//土地形状
//     char type;//收割机类型
// 	int S;//面积
// 	int xyz[200];//坐标
// }parameter;

#endif