#ifndef _HOME_H_
#define _HOME_H_

void draw_home01(void);//the page of n-w warehouse
//void draw_home00(void);//the page of Y-H warehouse
void draw_warehouse(void);//draw the picture of warehouse
void cot_mount(int x,int y);//draw the cotton in warehouse
void draw_trunk(void);//draw the trunk int the page
void in_warehouse(int count);//draw the board which show the cotton in warehouse
void detail_warehouse(void);
void press_home(void);//add the press moudule
#endif