#ifndef _WELCOME_H_
#define _WELCOME_H_

void draw_wel(void);              // Draw the whole welcome page
void draw_wel_tractors(void); // Draw the tractors in the welcome page
void draw_wel_cofield(void);  // Draw the cotton field in the welcome page
void draw_wel_buttons(void);  // Draw all the function buttons in welcome page
void enter_next(void);            // Complete the function of all buttons

#endif